blank_issues_enabled: false
contact_links:
  - name: Discord Server 
    url: https://discord.gg/
    about: discuss about all 
  - name: kc00l Discord server
    url: https://discord.gg/QHKjtFuG
    about: discuss about my mods and other modpacks
